//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DARE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DARESystem
    {
        public int SystemID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateInitiated { get; set; }
        public string HomeAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Description { get; set; }
        public string FamilyName { get; set; }
    }
}
