//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DARE.Models
{

    
    public partial class Note
    {
        public int NoteID { get; set; }
        public long UserID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public string Recipients { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Alert { get; set; }
        public Nullable<bool> PushNotification { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? AlertDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
