//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DARE.Models
{
    
    
    public partial class User
    {
        public User()
        {
            this.Notes = new HashSet<Note>();
            this.Privileges = new HashSet<Privilege>();
            this.Roles = new HashSet<Role>();
        }
    
        public long UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Hash { get; set; }
        public byte[] Salt { get; set; }
        public DateTime? CreationDate { get; set; }
        public DateTime? LastLoginDate { get; set; }
        public bool IsLocked { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public string ActivationToken { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string TempAccessCode { get; set; }
    
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Privilege> Privileges { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
